[package]
name = "nq-tokio-network"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
nq-core = { workspace = true }
tokio = { workspace = true, features = ["net"] }
tracing = { workspace = true }